image: Visual Studio 2017

version: 0.7.0-alpha{build}

install:
  - ps: dotnet restore  /p:Version=$Env:APPVEYOR_BUILD_VERSION

test_script:
  - ps: dotnet test /p:Version=$Env:APPVEYOR_BUILD_VERSION

artifacts:
  - path: 'src\**\*.nupkg'
    name: NuGet

